// license-header java merge-point
/* Autogenerated on 09/30/2012 15:47:17+0530 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::com.myjeeva.andromda.demo::service::SearchService::performSearch
 * STEREOTYPE:  WebService on SearchService
 * STEREOTYPE:  Service on SearchService
 * STEREOTYPE:  WebServiceOperation on performSearch
*/
package com.myjeeva.andromda.demo.service;

import com.myjeeva.andromda.demo.vo.Document;
import com.myjeeva.andromda.demo.vo.SearchResult;

/**
 * WebService Service Method Implementation for the SearchService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[com.myjeeva.andromda.demo.service.SearchService.performSearch].
 * 
 */

public class PerformSearchImpl
{
    /**
     * Constructor
     */
    public PerformSearchImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void performSearchSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SearchServiceWSDelegateTest and SearchServiceSEIImplTest
     */
    public static void performSearchTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the performSearch service method parameters on SearchService.
    * 
    * @param queryTerm datatype.String multiplicity=1..1
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void performSearchTransformInput(
        final String queryTerm
    )
    {

        if (queryTerm != null)
        {
            // transform(String);
        }
    }

   /**
    * Transforms input to an output response for performSearch service method on SearchService.
    * 
    * @return performSearchResponse SearchResult
    */
    public static SearchResult performSearchTransformResponse(
        /* Domain response to be transformed to service response */)
        // throws TransformationException?
    {
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
        SearchResult rtn = new SearchResult();

        // Property documents isMany has 5 properties: id name inStock price features
        Document documents = new Document();
        documents.setId("id");
        documents.setName("name");
        documents.setInStock(Boolean.TRUE);
        documents.setPrice(Double.valueOf(1));
        documents.getFeatures().add("features");
        rtn.getDocuments().add(documents);

        return rtn;
    }

    /** Create input test data for SearchService performSearch
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * queryTerm: String
     * @return performSearchReturn PerformSearch WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static PerformSearch performSearchCreateInput()
    {
        PerformSearch performSearchReturn = new PerformSearch();

        // parameter1 queryTermParam1 with 0 properties:
        String queryTermParam1 = "queryTerm";
        performSearchReturn.setQueryTerm(queryTermParam1);

        return performSearchReturn;
    }
}