// license-header java merge-point
/**
 * Generated by java cartridge ServiceImpl.vsl
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.myjeeva.andromda.demo.service;

/**
 * @see com.myjeeva.andromda.demo.service.SearchService
 */
public class SearchServiceImpl
    implements com.myjeeva.andromda.demo.service.SearchService
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6092999557775205657L;

    /**
     * @see com.myjeeva.andromda.demo.service.SearchService#performSearch(java.lang.String)
     */
    public com.myjeeva.andromda.demo.vo.SearchResultVO performSearch(java.lang.String queryTerm)
    {
        // TODO implement public com.myjeeva.andromda.demo.vo.SearchResultVO performSearch(java.lang.String queryTerm)
        return null;
    }

    /**
     * @see com.myjeeva.andromda.demo.service.SearchService#indexDocument(java.util.List<com.myjeeva.andromda.demo.vo.DocumentVO>)
     */
    public java.lang.Boolean indexDocument(java.util.List<com.myjeeva.andromda.demo.vo.DocumentVO> documents)
    {
        // TODO implement public java.lang.Boolean indexDocument(java.util.List<com.myjeeva.andromda.demo.vo.DocumentVO> documents)
        return null;
    }
}
