// license-header java merge-point
/* Autogenerated on 07/23/2012 17:27:04+0530 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::com.myjeeva.andromda.demo::service::SampleWebService::getServiceGreeting
 * STEREOTYPE:  WebService on SampleWebService
*/
package com.myjeeva.andromda.demo.service;

import com.myjeeva.andromda.demo.vo.GreetingVO;

/**
 * WebService Service Method Implementation for the SampleWebService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[com.myjeeva.andromda.demo.service.SampleWebService.getServiceGreeting].
 * 
 */

public class GetServiceGreetingImpl
{
    /**
     * Constructor
     */
    public GetServiceGreetingImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SampleWebServiceWSDelegateTest and SampleWebServiceSEIImplTest
     */
    public static void getServiceGreetingSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SampleWebServiceWSDelegateTest and SampleWebServiceSEIImplTest
     */
    public static void getServiceGreetingTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the getServiceGreeting service method parameters on SampleWebService.
    * 
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void getServiceGreetingTransformInput(
    )
    {
        // Documented empty block - avoid compiler warning - no method parameters
    }

   /**
    * Transforms input to an output response for getServiceGreeting service method on SampleWebService.
    * 
    * @return getServiceGreetingResponse GreetingVO
    */
    public static GreetingVO getServiceGreetingTransformResponse(
        /* Domain response to be transformed to service response */)
        // throws TransformationException?
    {
        // Dummy return value implementation with default values...
        // Iterate down through all complex types and create default dummy constructor and attribute values
        GreetingVO rtn = new GreetingVO();
        rtn.setMessage("message");

        return rtn;
    }

    /** Create input test data for SampleWebService getServiceGreeting
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * @return getServiceGreetingReturn GetServiceGreeting WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static GetServiceGreeting getServiceGreetingCreateInput()
    {
        GetServiceGreeting getServiceGreetingReturn = new GetServiceGreeting();

        return getServiceGreetingReturn;
    }
}