// license-header java merge-point
/* Autogenerated on 07/13/2012 18:42:36+0530 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::com.myjeeva.andromda.demo::service::SampleService::getDates
 * STEREOTYPE:  WebService on SampleService
*/
package com.myjeeva.andromda.demo.service;

import java.util.Calendar;
import java.util.Date;

import com.myjeeva.andromda.demo.vo.Dates;

/**
 * WebService Service Method Implementation for the SampleService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[com.myjeeva.andromda.demo.service.SampleService.getDates].
 * 
 */

public class GetDatesImpl
{
    /**
     * Constructor
     */
    public GetDatesImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SampleServiceWSDelegateTest and SampleServiceSEIImplTest
     */
    public static void getDatesSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SampleServiceWSDelegateTest and SampleServiceSEIImplTest
     */
    public static void getDatesTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the getDates service method parameters on SampleService.
    * 
    * @param start datatype.DateTime multiplicity=1..1
    * @param end datatype.DateTime multiplicity=1..1
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void getDatesTransformInput(
        final Date start
        , final Date end
    )
    {

        if (start != null)
        {
            // transform(Date);
        }

        if (end != null)
        {
            // transform(Date);
        }
    }

   /**
    * Transforms input to an output response for getDates service method on SampleService.
    * 
    * @return getDatesResponse Dates
    */
    public static Dates getDatesTransformResponse(Date start, Date end)
        // throws TransformationException?
    {
    	// Start and end gets incremented by 1 day for demo purpose
    	Calendar cal = Calendar.getInstance();
    	Dates rtn = new Dates();
    	
    	cal.setTime(start);
    	cal.add(Calendar.DATE, 1);
    	cal.getTime();
    	rtn.setStart(cal.getTime());
        
    	cal.setTime(end);
    	cal.add(Calendar.DATE, 1);
    	cal.getTime();
        rtn.setEnd(cal.getTime());

        return rtn;
    }

    /** Create input test data for SampleService getDates
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * start: Date
     * end: Date
     * @return getDatesReturn GetDates WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static GetDates getDatesCreateInput()
    {
        GetDates getDatesReturn = new GetDates();

        // parameter1 startParam1 with 0 properties:
        Date startParam1 = new Date();
        getDatesReturn.setStart(startParam1);

        // parameter2 endParam2 with 0 properties:
        Date endParam2 = new Date();
        getDatesReturn.setEnd(endParam2);

        return getDatesReturn;
    }
}