// license-header java merge-point
/* Autogenerated on 07/13/2012 18:42:37+0530 by AndroMDA!
 *
 * TEMPLATE:    jaxws\WebServiceMethodImpl.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::com.myjeeva.andromda.demo::service::SampleService::getServiceGreeting
 * STEREOTYPE:  WebService on SampleService
*/
package com.myjeeva.andromda.demo.service;

import com.myjeeva.andromda.demo.vo.Greeting;

/**
 * WebService Service Method Implementation for the SampleService
 * service org.andromda.cartridges.webservice.metafacades.WebServiceOperationLogicImpl[com.myjeeva.andromda.demo.service.SampleService.getServiceGreeting].
 * 
 */

public class GetServiceGreetingImpl
{
    /**
     * Constructor
     */
    public GetServiceGreetingImpl()
    {
        //Documented empty code block - avoid compiler warning
    }

    /**
     * Delegate for TestCase SampleServiceWSDelegateTest and SampleServiceSEIImplTest
     */
    public static void getServiceGreetingSetUp()
    {
        // Insert your custom code here for additional required unit test case setup for service method
    }

    /**
     * Delegate for TestCase SampleServiceWSDelegateTest and SampleServiceSEIImplTest
     */
    public static void getServiceGreetingTearDown()
    {
        // Insert your custom code here for additional required unit test case tear down for service method
    }

   /**
    * Transforms the getServiceGreeting service method parameters on SampleService.
    * 
    * Replace void with transformed type, use target.set() values to create transformation
    */
    public static void getServiceGreetingTransformInput(
    )
    {
        // Documented empty block - avoid compiler warning - no method parameters
    }

   /**
    * Transforms input to an output response for getServiceGreeting service method on SampleService.
    * 
    * @return getServiceGreetingResponse Greeting
    */
    public static Greeting getServiceGreetingTransformResponse(
        /* Domain response to be transformed to service response */)
        // throws TransformationException?
    {
        Greeting rtn = new Greeting();
        rtn.setMessage("Webservice Demo Project Greeting you!");

        return rtn;
    }

    /** Create input test data for SampleService getServiceGreeting
     * Used by webservice WSClient (against service) and core service WSDelegateTest (against implementation).
     * Return wrapped parameters:
     * @return getServiceGreetingReturn GetServiceGreeting WS Input parameter wrapper (assumes wrapped WSDL)
     **/
    public static GetServiceGreeting getServiceGreetingCreateInput()
    {
        GetServiceGreeting getServiceGreetingReturn = new GetServiceGreeting();

        return getServiceGreetingReturn;
    }
}