// license-header java merge-point
/* Autogenerated on 09/30/2012 15:47:17+0530 by AndroMDA, can be edited
 *
 * TEMPLATE: jaxws/JettyServer.java.vsl in andromda-webservices-cartridge
 * SERVICE:  SearchService
*/

import org.eclipse.jetty.server.Connector;
import org.eclipse.jetty.server.Handler;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.handler.DefaultHandler;
import org.eclipse.jetty.server.handler.HandlerCollection;
import org.eclipse.jetty.server.nio.SelectChannelConnector;
import org.eclipse.jetty.webapp.WebAppContext;

/**
 * Simple class to start a web server with one simple class, to test web services
 * and web server configuration. Based on CXF Samples: java_first_spring_support
 */
public class JettyServer
{
    /**
     * @throws Exception
     */
    protected JettyServer() throws Exception
    {
        System.out.println("Starting Jetty Server");

        /** See http://wiki.eclipse.org/Jetty/Tutorial/Embedding_Jetty
         * Important: This code simply starts up a servlet container and adds
         * the web application in src/webapp to it. Normally you would be using
         * Jetty or Tomcat and have the webapp packaged as a WAR. This is simply
         * a convenience so you do not need to configure your servlet container to
         * see CXF in action or run integration tests!. For additional logging and debugging, add:
         * -Djava.util.logging.config.file=%CXF_HOME%/etc/logging.properties.
         * See https://cwiki.apache.org/confluence/display/CXF20DOC/Debugging+and+Logging
         * Or add mda/log4j.xml to the test classpath.
         */
        Server server = new Server();

        SelectChannelConnector connector = new SelectChannelConnector();
        connector.setPort(9090);
        server.setConnectors(new Connector[] {connector});

        WebAppContext webappcontext = new WebAppContext();
        webappcontext.setContextPath("/rest-webservice-webservice");

        webappcontext.setWar("src/main/webapp");

        HandlerCollection handlers = new HandlerCollection();
        handlers.setHandlers(new Handler[] {webappcontext, new DefaultHandler()});

        //EventLogInInterceptor myInterceptor = new EventLogInInterceptor();
        //org.apache.cxf.endpoint.Server CXFserver = serverFactoryBean.create();
        //CXFserver.getEndpoint().getInInterceptors().add(myInterceptor);

        server.setHandler(handlers);
        server.start();
        System.out.println("Jetty Server running on port 9090 under context rest-webservice-webservice...");
        server.join();
    }

    /**
     * @param args
     * @throws Exception
     */
    public static void main(String args[]) throws Exception
    {
        new JettyServer();
    }
}