// license-header java merge-point
/* Autogenerated on 10/04/2012 00:33:24+0530 by AndroMDA
 *
 * TEMPLATE:    jaxws/WebServiceSEIImplTest.vsl in andromda-webservices-cartridge
 * MODEL CLASS: AndroMDAModel::com.myjeeva.andromda.demo::service::SearchService
 * STEREOTYPE:  WebService
 * STEREOTYPE:  Service
*/
package com.myjeeva.andromda.demo.service;

import junit.framework.TestCase;
import junit.textui.TestRunner;

/**
 * WebService Service Delegate Test for the SearchService service.
 * 
 */

public class SearchServiceSEIImplTest extends TestCase
{
    /**
     * Constructor
     * @param name test case name
     */
    public SearchServiceSEIImplTest(String name)
    {
        super(name);
    }

    /**
     * No arg Constructor. Delegates to constructor(String) with test case name
     */
    public SearchServiceSEIImplTest()
    {
        super("SearchService");
    }

    /**
     * @see junit.framework.TestCase#setUp()
     */
    @Override
    protected void setUp() throws Exception
    {
        super.setUp();
    }

    /**
     * @see junit.framework.TestCase#tearDown()
     */
    @Override
    protected void tearDown() throws Exception
    {
        super.tearDown();
    }

    /**
     * Test method for {@link com.myjeeva.andromda.demo.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplIndexDocument()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        com.myjeeva.andromda.demo.service.IndexDocumentImpl.indexDocumentSetUp();
        com.myjeeva.andromda.demo.service.IndexDocument indexDocumentInput = com.myjeeva.andromda.demo.service.IndexDocumentImpl.indexDocumentCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.indexDocument with " + indexDocumentInput);
            java.lang.Boolean rtn = delegate.indexDocument(
             indexDocumentInput.getDocuments()  // java.util.List<com.myjeeva.andromda.demo.vo.DocumentVO>
        );
        System.out.println("SearchServiceSEIImpl.indexDocument" + " returned " + rtn);
        com.myjeeva.andromda.demo.service.IndexDocumentImpl.indexDocumentTearDown();
    }

    /**
     * Test method for {@link com.myjeeva.andromda.demo.service.SearchServiceSEIImpl#SearchServiceSEIImpl()}.
     */
    public void testSearchServiceSEIImplPerformSearch()
    {
        // TestCase.setUp and tearDown methods for each individual service method test
        com.myjeeva.andromda.demo.service.PerformSearchImpl.performSearchSetUp();
        com.myjeeva.andromda.demo.service.PerformSearch performSearchInput = com.myjeeva.andromda.demo.service.PerformSearchImpl.performSearchCreateInput();
        SearchServiceSEIImpl delegate = new SearchServiceSEIImpl();
        System.out.println("Invoking SearchServiceSEIImpl.performSearch with " + performSearchInput);
            com.myjeeva.andromda.demo.vo.SearchResultVO rtn = delegate.performSearch(
             performSearchInput.getQueryTerm()  // java.lang.String
        );
        System.out.println("SearchServiceSEIImpl.performSearch" + " returned " + rtn);
        com.myjeeva.andromda.demo.service.PerformSearchImpl.performSearchTearDown();
    }

    /**
     * main() method to run the test with the textual test runner.
     * @param args Not used
     */
    public static void main(final String[] args)
    {
        TestRunner.run(SearchServiceSEIImplTest.class);
    }
}

