package com.myjeeva.andromda.demo.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-10-04T00:52:57.712+05:30
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "SearchService", 
                  wsdlLocation = "/Users/jeeva/Documents/svn/rest-webservice/mda/../webservice/src/main/webapp/wsdl/SearchService.wsdl",
                  targetNamespace = "http://service.demo.andromda.myjeeva.com/") 
public class SearchServiceSEIClient extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.demo.andromda.myjeeva.com/", "SearchService");
    public final static QName SearchService = new QName("http://service.demo.andromda.myjeeva.com/", "SearchService");
    static {
        URL url = SearchServiceSEIClient.class.getResource("/Users/jeeva/Documents/svn/rest-webservice/mda/../webservice/src/main/webapp/wsdl/SearchService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(SearchServiceSEIClient.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/jeeva/Documents/svn/rest-webservice/mda/../webservice/src/main/webapp/wsdl/SearchService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SearchServiceSEIClient(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SearchServiceSEIClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchServiceSEIClient() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns SearchServiceSEI
     */
    @WebEndpoint(name = "SearchService")
    public SearchServiceSEI getSearchService() {
        return super.getPort(SearchService, SearchServiceSEI.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchServiceSEI
     */
    @WebEndpoint(name = "SearchService")
    public SearchServiceSEI getSearchService(WebServiceFeature... features) {
        return super.getPort(SearchService, SearchServiceSEI.class, features);
    }

}
