
package com.myjeeva.andromda.demo.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-30T20:36:16.425+05:30
 * Generated source version: 2.6.2
 * 
 */
 
public class SearchServiceSEI_SearchService_Server{

    protected SearchServiceSEI_SearchService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new SearchServiceSEIImpl();
        String address = "http://localhost:9090/rest-webservice-webservice/services/SearchService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new SearchServiceSEI_SearchService_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
