
package com.myjeeva.andromda.demo.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-30T20:36:16.308+05:30
 * Generated source version: 2.6.2
 * 
 */
public final class SearchServiceSEI_SearchService_Client {

    private static final QName SERVICE_NAME = new QName("http://service.demo.andromda.myjeeva.com/", "SearchService");

    private SearchServiceSEI_SearchService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SearchServiceSEIClient.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SearchServiceSEIClient ss = new SearchServiceSEIClient(wsdlURL, SERVICE_NAME);
        SearchServiceSEI port = ss.getSearchService();  
        

        System.exit(0);
    }

}
